apiVersion: v1
kind: Service
metadata:
  name: weddingplanner-service
spec:
  selector:
    app: weddingplanner  # This should match the label in your deployment
  ports:
  - protocol: TCP
    port: 80              # Port exposed by the service
    targetPort: 8080      # Port on the container
  type: LoadBalancer     # Change to NodePort if using local Kubernetes
